#!/usr/bin/env bash
# This script parses /etc/passwd and displays username, user id, and home directory

# shellcheck disable=SC2034
while IFS=":" read -r username password uid gid info home shell; do
    echo "${username}:${uid}:${home}"
done < /etc/passwd
