#!/usr/bin/env bash
# This script parses /etc/passwd and displays username, user id, and home directory

while IFS=":" read -r username password_to_discard uid gid_to_discard info_to_discard home user_shell; do
    echo "${username}:${uid}:${home}"
done < /etc/passwd
