#!/usr/bin/env bash
# This script checks the properties of the file named 'school' passed as an argument

if [ "$#" -eq 0 ]; then
    exit 1
fi

filename=$1

if [ -e "$filename" ]; then
    echo "school file exists"
    
    if [ -s "$filename" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    
    if [ -f "$filename" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
