#!/usr/bin/env bash
# This script creates a PID tracking file and registers custom cleanups for SIGTERM, SIGINT, and SIGQUIT

pid_file="/var/run/myscript.pid"

echo "$$" > "$pid_file"

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm -f "$pid_file"; exit' SIGTERM
trap 'rm -f "$pid_file"; exit' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done

