#!/usr/bin/env bash
# This script runs indefinitely and hooks the SIGTERM signal to output a unique phrase

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done

